Sync upstream
OutSystems/cordova-plugin-statusbar pull request #23
Opened 2024-08-08 17:29 UTC by andredestro

### Platforms affected

### Motivation and Context

### Description

### Testing

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

2024-08-08 17:43 UTC, markemer approved these changes, later dismissed

2024-08-08 17:46 UTC, markemer commented
Wait this still has the `macos-11` stuff in it - the android stuff looks better, though.

2024-08-08 17:48 UTC, markemer commented
Yeah, these commits appear to be missing: https://github.com/apache/cordova-plugin-statusbar/pull/271 - but they're merged upstream - hrm.

2024-08-08 17:51 UTC, markemer requested changes
Yeah - we need to merge HEAD instead of 4.0.0, or cherry pick the new PRs to get CI to work.

2024-08-08 18:00 UTC, jcesarmobile commented on src/android/StatusBar.java
> -        }
This seems outsystems specific, should not be removed

2024-08-08 18:11 UTC, jcesarmobile commented on src/android/StatusBar.java
> -        }
nevermind, the code is still there, just missing the `isStatusBarOverlayingWebview` declaration

2024-08-08 18:12 UTC, jcesarmobile requested changes
`ACTION_IS_OVERLAYS_WEB_VIEW` and `ACTION_GET_HEIGHT` have been added to the switch statement, but they are not declared.

2024-08-09 13:54 UTC, jcesarmobile approved these changes

2024-08-09 15:31 UTC, markemer approved these changes

2024-08-09 15:35 UTC, merged