Updated StatusBar to v4.2.1 (merged master into outsystems branch)
OutSystems/cordova-plugin-statusbar pull request #3
Opened 2018-02-07 16:55 UTC by pmaroco

2018-02-07 17:03 UTC, bgracio approved these changes

2018-02-08 14:01 UTC, luissilvaos requested changes
Check my comments please

2018-02-08 14:01 UTC, luissilvaos commented on src/android/StatusBar.java
> +        if ("overlaysWebView".equals(action)) {
This condition is duplicated

2018-02-08 17:03 UTC, pmaroco commented on src/android/StatusBar.java
> +        if ("overlaysWebView".equals(action)) {
Fixed!

2018-02-09 15:28 UTC, vmfo22 approved these changes

2018-02-14 10:43 UTC, EiyuuZack approved these changes

2018-02-14 11:45 UTC, luissilvaos requested changes
Check my comments please.

2018-02-14 11:45 UTC, luissilvaos commented on src/android/StatusBar.java
> -                        ActivityAssistant.getInstance().applyGlobalLayoutListener();
You miss the merge of this action and lost important code here.

2018-02-22 16:24 UTC, luissilvaos approved these changes

2018-02-22 16:44 UTC, merged